### ISSUE TITLE
Config path is set at compile time

### ISSUE THREAD

**Issue by arnimattr** [rv178/bday#3]
It's me again, with a few issues. They aren't major issues, I just wanted to let you know.
- I noticed that [using `env!("HOME")`](https://github.com/rv178/bday/blob/243140bf185df38671a536566b3c166aae250b5c/src/main.rs#L36) uses the environment variable at compile time, so if you compile the executable and send it to someone else, it won't work. To fix that, use `env::var("HOME)"` instead
- `env::var("HOME")` doesn't work on Windows. I assume this isn't important to you since you run Linux, but just for context, starship uses [this](https://github.com/starship/starship/blob/98089bf005e97a22817eb3690b987db907f72fc0/src/utils.rs#L556) to get the home directory path

**Comment by rv178** [comment]
ooh I see, thanks for the heads up!
